---
# Lance le proxy HTTP (frontend)

- name: Launch the HTTPD container
  docker_container:
    name: frontend
    image: karatann/frontend:latest
    pull: yes
    networks:
      - name: front-network
