---
# tasks/main.yml

# 1. Installer les prérequis pour Docker
- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-venv
    state: latest
    update_cache: yes

# 2. Ajouter la clé GPG officielle de Docker
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

# 3. Ajouter le dépôt APT stable de Docker
- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"
    state: present
    update_cache: yes

# 4. Installer Docker
- name: Install Docker
  apt:
    name: docker-ce
    state: present

# 5. Installer Python3 et pip3
- name: Install Python3 and pip3
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Create a virtual environment for Docker SDK
  command: python3 -m venv /opt/docker_venv
  args:
    creates: /opt/docker_venv # Ne s'exécute que si le répertoire n'existe pas

- name: Install Docker SDK for Python in virtual environment
  command: /opt/docker_venv/bin/pip install docker

- name: Make sure Docker is running
  service:
    name: docker
    state: started
  tags: docker
