name: Merge Develop to Main

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "corretto"

      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: backend/simple-api-student

      - name: Extract version from pom.xml
        id: extract-version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
        working-directory: backend/simple-api-student
        # Étape 4 : Extraire la version du `pom.xml` et la stocker dans la variable d'environnement `VERSION`.

  build-and-push-docker-image:
    needs: test-and-build
    # Ce job est exécuté uniquement si le job précédent (`test-and-build`) réussit.

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Étape 1 : Récupérer le code du dépôt.

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./backend/simple-api-student
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:${{ env.VERSION }}
          # Tag : Utilise la version extraite du `pom.xml`.
          push: true
          # Push : Pousse l'image sur Docker Hub.

      - name: Build and push database image
        uses: docker/build-push-action@v3
        with:
          context: ./db
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:${{ env.VERSION }}
          # Tag : Utilise la version extraite du `pom.xml`.
          push: true
          # Push : Pousse l'image sur Docker Hub.

      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./http
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-frontend:${{ env.VERSION }}
          # Tag : Utilise la version extraite du `pom.xml`.
          push: true
          # Push : Pousse l'image sur Docker Hub.
