name: Merge Develop to Main

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "corretto"

      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: backend/simple-api-student

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils
        # Étape : Installer xmllint pour manipuler le XML.

      - name: Extract version from pom.xml
        id: extract-version
        run: |
          VERSION=$(xmllint --xpath "/[local-name()='project']/[local-name()='version']/text()" backend/simple-api-student/pom.xml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

  build-and-push-docker-image:
    needs: test-and-build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./backend/simple-api-student
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:${{ env.VERSION }}
          push: true

      - name: Build and push database image
        uses: docker/build-push-action@v3
        with:
          context: ./db
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:${{ env.VERSION }}
          push: true

      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./http
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-frontend:${{ env.VERSION }}
          push: true
