name: Validate Merge Request

on:
  pull_request:
    branches:
      - develop

jobs:
  test-and-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "corretto"

      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: backend/simple-api-student

  sonar-analysis:
    name: SonarCloud Analysis
    needs: test-and-build

    if: ${{ github.event.pull_request.base.ref == 'develop' }}

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify sonar:sonar -f backend/simple-api-student/pom.xml
